#!env php
<?php

use MarcW\Silence\Console\Application;
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Symfony\Component\DependencyInjection\ContainerBuilder;

require_once __DIR__.'/config/bootstrap.php';

$application = new Application();

$application->add($container->get(\MarcW\Silence\Command\RssGenerateCommand::class));
$application->add($container->get(\MarcW\Silence\Command\ChannelCreateCommand::class));
$application->add($container->get(\MarcW\Silence\Command\ChannelListCommand::class));
$application->add($container->get(\MarcW\Silence\Command\ChannelShowCommand::class));
$application->add($container->get(\MarcW\Silence\Command\ChannelEditCommand::class));
$application->add($container->get(\MarcW\Silence\Command\EpisodeCreateCommand::class));
$application->add($container->get(\MarcW\Silence\Command\EpisodeListCommand::class));
$application->add($container->get(\MarcW\Silence\Command\EpisodeShowCommand::class));
$application->add($container->get(\MarcW\Silence\Command\EpisodeEditCommand::class));
$application->run();
