#!env php
<?php

use MarcW\Podcast\Console\Application;
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;

require_once __DIR__.'/config/bootstrap.php';

$application = new Application();

$application->add(new \MarcW\Podcast\Command\GenerateCommand());
$application->add(new \MarcW\Podcast\Command\NewChannelCommand());
$application->run();
